dev:
  app_port: 8080
  debug: true
  disk_free_threshold: 15
  service_name: python     # used by service_check.py

prod:
  app_port: 80
  debug: false
  disk_free_threshold: 20
  service_name: python     # change per your app in real use
