dev:
  app_port: 8080
  debug: true
  disk_free_threshold: 15
  service_name: python

  # Model & data locations
  model_source: "s3"                # "s3" | "local"
  model_s3_bucket: "my-dev-bucket"
  model_s3_prefix: "models/project-x/"
  model_local_dir: "artifacts/models"
  model_current_symlink: "artifacts/current_model.pkl"

  # Reporting & notifications
  report_dir: "reports"
  report_email_to: "dipikarakesh.verma@pfizer.com"
  report_email_from: "dipikarakesh.verma@pfizer.com"

prod:
  app_port: 80
  debug: false
  disk_free_threshold: 20
  service_name: python

  model_source: "s3"
  model_s3_bucket: "my-prod-bucket"
  model_s3_prefix: "models/project-x/"
  model_local_dir: "artifacts/models"
  model_current_symlink: "artifacts/current_model.pkl"

  report_dir: "reports"
  report_email_to: "dipikarakesh.verma@pfizer.com"
  report_email_from: "dipikarakesh.verma@pfizer.com"
